// Sprint 27: Storage Key Registry
// Central registry of ALL storage keys used across the app.
// Re-exports STORAGE_KEYS from storage.ts and provides validation helpers.
// Any new storage key MUST be added to STORAGE_KEYS in storage.ts — no magic strings.

export { STORAGE_KEYS, dateKey } from './storage';
export type { StorageKey } from './storage';

import { STORAGE_KEYS } from './storage';

/**
 * All registered storage key values (flat list).
 * Used for validating that no magic strings slip through.
 */
export const ALL_STORAGE_KEY_VALUES: string[] = Object.values(STORAGE_KEYS);

/**
 * All date-keyed log prefixes (keys that use dateKey()).
 * These produce keys like "dub.log.food.2026-01-15".
 */
export const DATE_KEYED_LOG_PREFIXES: string[] = [
  STORAGE_KEYS.LOG_FOOD,
  STORAGE_KEYS.LOG_WATER,
  STORAGE_KEYS.LOG_CAFFEINE,
  STORAGE_KEYS.LOG_WORKOUT,
  STORAGE_KEYS.LOG_STRENGTH,
  STORAGE_KEYS.LOG_STEPS,
  STORAGE_KEYS.LOG_BODY,
  STORAGE_KEYS.LOG_SLEEP,
  STORAGE_KEYS.LOG_MOOD,
  STORAGE_KEYS.LOG_GRATITUDE,
  STORAGE_KEYS.LOG_MEDITATION,
  STORAGE_KEYS.LOG_STRESS,
  STORAGE_KEYS.LOG_THERAPY,
  STORAGE_KEYS.LOG_SUPPLEMENTS,
  STORAGE_KEYS.LOG_SUBSTANCES,
  STORAGE_KEYS.LOG_SEXUAL,
  STORAGE_KEYS.LOG_CYCLE,
  STORAGE_KEYS.LOG_DIGESTIVE,
  STORAGE_KEYS.LOG_PERSONALCARE,
  STORAGE_KEYS.LOG_INJURY,
  STORAGE_KEYS.LOG_BLOODWORK,
  STORAGE_KEYS.LOG_GLUCOSE,
  STORAGE_KEYS.LOG_BP,
  STORAGE_KEYS.LOG_HABITS,
  STORAGE_KEYS.LOG_REPS,
  STORAGE_KEYS.LOG_DOCTOR_VISITS,
  STORAGE_KEYS.LOG_ALLERGIES,
  STORAGE_KEYS.LOG_SOCIAL,
  STORAGE_KEYS.LOG_SUNLIGHT,
  STORAGE_KEYS.LOG_MOBILITY,
  STORAGE_KEYS.LOG_JOURNAL,
  STORAGE_KEYS.LOG_PERIMENOPAUSE,
  STORAGE_KEYS.LOG_BREASTFEEDING,
  STORAGE_KEYS.LOG_MIGRAINE,
  STORAGE_KEYS.LOG_MOOD_MENTAL,
  STORAGE_KEYS.LOG_BODY_MEASUREMENTS,
  STORAGE_KEYS.LOG_MEDICATIONS,
  STORAGE_KEYS.LOG_CUSTOM,
];

/**
 * All exportable data key prefixes (used by export service).
 * Excludes therapy content (firewall), audit logs, and caches.
 */
export const EXPORTABLE_DATA_PREFIXES: string[] = [
  STORAGE_KEYS.LOG_FOOD,
  STORAGE_KEYS.LOG_WATER,
  STORAGE_KEYS.LOG_CAFFEINE,
  STORAGE_KEYS.LOG_WORKOUT,
  STORAGE_KEYS.LOG_STRENGTH,
  STORAGE_KEYS.LOG_STEPS,
  STORAGE_KEYS.LOG_BODY,
  STORAGE_KEYS.LOG_SLEEP,
  STORAGE_KEYS.LOG_MOOD,
  STORAGE_KEYS.LOG_GRATITUDE,
  STORAGE_KEYS.LOG_MEDITATION,
  STORAGE_KEYS.LOG_STRESS,
  // LOG_THERAPY intentionally excluded — firewall
  STORAGE_KEYS.LOG_SUPPLEMENTS,
  STORAGE_KEYS.LOG_SUBSTANCES,
  // LOG_SEXUAL intentionally excluded — private
  STORAGE_KEYS.LOG_CYCLE,
  STORAGE_KEYS.LOG_DIGESTIVE,
  STORAGE_KEYS.LOG_PERSONALCARE,
  STORAGE_KEYS.LOG_INJURY,
  STORAGE_KEYS.LOG_BLOODWORK,
  STORAGE_KEYS.LOG_GLUCOSE,
  STORAGE_KEYS.LOG_BP,
  STORAGE_KEYS.LOG_HABITS,
  STORAGE_KEYS.LOG_REPS,
  STORAGE_KEYS.LOG_DOCTOR_VISITS,
  STORAGE_KEYS.LOG_ALLERGIES,
  STORAGE_KEYS.LOG_SOCIAL,
  STORAGE_KEYS.LOG_SUNLIGHT,
  STORAGE_KEYS.LOG_MOBILITY,
  STORAGE_KEYS.LOG_JOURNAL,
  STORAGE_KEYS.LOG_PERIMENOPAUSE,
  STORAGE_KEYS.LOG_BREASTFEEDING,
  STORAGE_KEYS.LOG_MIGRAINE,
  STORAGE_KEYS.LOG_MOOD_MENTAL,
  STORAGE_KEYS.LOG_BODY_MEASUREMENTS,
  STORAGE_KEYS.LOG_MEDICATIONS,
  STORAGE_KEYS.LOG_CUSTOM,
];

/**
 * Keys that should be cleared by "Clear All Data" (everything user-generated).
 * Excludes auth tokens and onboarding state (those require separate reset).
 */
export const CLEARABLE_DATA_KEYS: string[] = [
  // All date-keyed log prefixes (matching by prefix)
  ...DATE_KEYED_LOG_PREFIXES,
  // Aggregates
  STORAGE_KEYS.DAILY_SUMMARY,
  STORAGE_KEYS.WEEKLY_SUMMARY,
  STORAGE_KEYS.MONTHLY_SUMMARY,
  STORAGE_KEYS.RECOVERY,
  STORAGE_KEYS.STREAKS,
  STORAGE_KEYS.SOBRIETY,
  STORAGE_KEYS.COMPLIANCE,
  // Caches
  STORAGE_KEYS.FOOD_CACHE,
  STORAGE_KEYS.FOOD_FAVORITES,
  STORAGE_KEYS.FOOD_TEMPLATES,
  STORAGE_KEYS.FOOD_RECENT,
  STORAGE_KEYS.MY_FOODS,
  STORAGE_KEYS.SUPPLEMENT_STACKS,
  STORAGE_KEYS.MY_SUPPLEMENTS,
  STORAGE_KEYS.BARCODE_CACHE,
  STORAGE_KEYS.FOOD_SEARCH_CACHE,
  STORAGE_KEYS.WEATHER_CACHE,
  STORAGE_KEYS.RECENT_ACTIVITIES,
  // Coach
  STORAGE_KEYS.COACH_HISTORY,
  STORAGE_KEYS.COACH_PATTERNS,
  STORAGE_KEYS.FEEDBACK_LOG,
  // Settings (user-configured)
  STORAGE_KEYS.SETTINGS_HABITS,
  STORAGE_KEYS.SETTINGS_DAILY_GOALS,
  STORAGE_KEYS.SETTINGS_SLEEP_SCHEDULE,
  STORAGE_KEYS.SETTINGS_ENABLED_CATEGORIES,
  STORAGE_KEYS.SETTINGS_LOG_SECTIONS_COLLAPSED,
  STORAGE_KEYS.SETTINGS_QUICK_ACCESS,
  STORAGE_KEYS.SETTINGS_DASHBOARD_TILES,
  STORAGE_KEYS.SETTINGS_HYDRATION_GOAL,
  STORAGE_KEYS.SETTINGS_UNITS,
  STORAGE_KEYS.SETTINGS_NOTIFICATIONS,
  STORAGE_KEYS.SETTINGS_MEDICATION_LIST,
  STORAGE_KEYS.SETTINGS_BODY_MEAS_WEIGHT_UNIT,
  STORAGE_KEYS.SETTINGS_BODY_MEAS_UNIT,
  STORAGE_KEYS.SETTINGS_LAST_ZIP_CODE,
  STORAGE_KEYS.INGREDIENT_FLAGS,
  STORAGE_KEYS.USER_MACROS,
  // UI state
  STORAGE_KEYS.FAVORITE_TAGS,
  STORAGE_KEYS.LAST_ENTRY,
  STORAGE_KEYS.MARKETPLACE_DISMISSED,
  STORAGE_KEYS.MARKETPLACE_PURCHASES,
  STORAGE_KEYS.MILESTONES_ACKNOWLEDGED,
  STORAGE_KEYS.MOOD_RESOURCE_DISMISSED,
  STORAGE_KEYS.NOTIFICATION_PREFS,
  STORAGE_KEYS.EOD_DISMISSED,
  STORAGE_KEYS.EOD_SKIP_COUNTS,
  STORAGE_KEYS.STRENGTH_MODE_PREF,
  STORAGE_KEYS.PHOTOS_PROGRESS,
  // Recipes
  STORAGE_KEYS.MY_RECIPES,
  STORAGE_KEYS.PROFILE_ALLERGIES,
];

/**
 * Validate that a storage key follows the dub. namespace convention.
 */
export function isValidStorageKey(key: string): boolean {
  return key.startsWith('dub.');
}
