// Sample marketplace product data and influencer data
// Phase 22: Marketplace, Influencer System, and Polish
// 16 product categories with contextual triggers
// This is placeholder data -- real products would come from a backend/CMS

import type { Product, Influencer } from '../../types/marketplace';

const AFFILIATE_DISCLOSURE = {
  type: 'affiliate' as const,
  text: 'This is an affiliate link. DUB_AI may earn a commission if you purchase through this link.',
};

export const MARKETPLACE_PRODUCTS: Product[] = [
  // Body Composition
  {
    id: 'prod_body_001',
    name: 'Smart Body Composition Scale',
    description: 'Measures weight, body fat %, muscle mass, BMI, and more. Syncs via Bluetooth.',
    category: 'body_composition',
    brand: 'Withings',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/body-scale',
    affiliate_partner: 'amazon',
    price: 99.99,
    price_currency: 'USD',
    contextual_trigger: 'goal_onboarding',
    trigger_reason: 'You were shown this because you set a body composition goal during onboarding.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: null, max_age: null, sex: null, tiers: null, goals: ['LOSE', 'GAIN', 'RECOMP'] },
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prod_body_002',
    name: 'Body Measurement Tape',
    description: 'Retractable soft tape measure for tracking body measurements accurately.',
    category: 'body_composition',
    brand: 'MyoTape',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/tape-measure',
    affiliate_partner: 'amazon',
    price: 12.99,
    price_currency: 'USD',
    contextual_trigger: 'goal_onboarding',
    trigger_reason: 'You were shown this because you set a body composition goal during onboarding.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: null, max_age: null, sex: null, tiers: null, goals: ['LOSE', 'GAIN', 'RECOMP'] },
    created_at: '2024-01-01T00:00:00Z',
  },

  // Nutrition Tools
  {
    id: 'prod_nutr_001',
    name: 'Digital Kitchen Food Scale',
    description: 'Precision food scale with tare function. Essential for accurate macro tracking.',
    category: 'nutrition_tools',
    brand: 'OXO',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/food-scale',
    affiliate_partner: 'amazon',
    price: 29.99,
    price_currency: 'USD',
    contextual_trigger: 'goal_onboarding',
    trigger_reason: 'You were shown this because you selected a weight loss goal. A food scale improves tracking accuracy.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: null, max_age: null, sex: null, tiers: ['precision', 'structured'], goals: ['LOSE'] },
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prod_nutr_002',
    name: 'Meal Prep Containers (10-Pack)',
    description: 'BPA-free compartmentalized containers for weekly meal prep.',
    category: 'nutrition_tools',
    brand: 'PrepNaturals',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/meal-prep',
    affiliate_partner: 'amazon',
    price: 19.99,
    price_currency: 'USD',
    contextual_trigger: 'behavior_pattern',
    trigger_reason: 'You were shown this because your logging patterns suggest frequent restaurant meals. Meal prep can help with nutrition goals.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: null, max_age: null, sex: null, tiers: null, goals: null },
    created_at: '2024-01-01T00:00:00Z',
  },

  // Supplements
  {
    id: 'prod_supp_001',
    name: 'Whey Protein Isolate',
    description: 'Low-carb whey isolate, 25g protein per serving. Third-party tested.',
    category: 'supplements',
    brand: 'Optimum Nutrition',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/whey-protein',
    affiliate_partner: 'amazon',
    price: 34.99,
    price_currency: 'USD',
    contextual_trigger: 'behavior_pattern',
    trigger_reason: 'You were shown this because your protein intake has been consistently below your target over the past week.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: 16, max_age: null, sex: null, tiers: null, goals: ['GAIN', 'RECOMP', 'LOSE'] },
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prod_supp_002',
    name: 'Vitamin D3 5000 IU',
    description: 'High-potency Vitamin D3 supplement. Supports bone health and immune function.',
    category: 'supplements',
    brand: 'NatureWise',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/vitamin-d',
    affiliate_partner: 'amazon',
    price: 14.99,
    price_currency: 'USD',
    contextual_trigger: 'deficit_detection',
    trigger_reason: 'You were shown this because you logged low Vitamin D in your recent bloodwork entries.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: null, max_age: null, sex: null, tiers: null, goals: null },
    created_at: '2024-01-01T00:00:00Z',
  },

  // Hydration
  {
    id: 'prod_hydr_001',
    name: 'Insulated Water Bottle (32oz)',
    description: 'Double-wall vacuum insulated. Keeps water cold 24 hours.',
    category: 'hydration',
    brand: 'Hydro Flask',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/water-bottle',
    affiliate_partner: 'amazon',
    price: 44.95,
    price_currency: 'USD',
    contextual_trigger: 'feature_adoption',
    trigger_reason: 'You were shown this because you started tracking water intake.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: null, max_age: null, sex: null, tiers: null, goals: null },
    created_at: '2024-01-01T00:00:00Z',
  },

  // Strength Equipment
  {
    id: 'prod_str_001',
    name: 'Adjustable Dumbbell Set',
    description: 'Replaces 15 sets of weights. 5-52.5 lbs per dumbbell.',
    category: 'strength_equipment',
    brand: 'Bowflex',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/dumbbells',
    affiliate_partner: 'amazon',
    price: 349.00,
    price_currency: 'USD',
    contextual_trigger: 'goal_onboarding',
    trigger_reason: 'You were shown this because you set a strength or muscle gain goal.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: 16, max_age: null, sex: null, tiers: null, goals: ['GAIN', 'RECOMP'] },
    created_at: '2024-01-01T00:00:00Z',
  },

  // Cardio Equipment
  {
    id: 'prod_card_001',
    name: 'Jump Rope (Weighted)',
    description: 'Adjustable weighted jump rope for cardio and coordination training.',
    category: 'cardio_equipment',
    brand: 'Crossrope',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/jump-rope',
    affiliate_partner: 'amazon',
    price: 49.99,
    price_currency: 'USD',
    contextual_trigger: 'goal_onboarding',
    trigger_reason: 'You were shown this because cardio equipment complements your fitness goals.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: null, max_age: null, sex: null, tiers: null, goals: ['LOSE', 'MAINTAIN'] },
    created_at: '2024-01-01T00:00:00Z',
  },

  // Wearables
  {
    id: 'prod_wear_001',
    name: 'Fitness Tracker with HR Monitor',
    description: 'Tracks steps, heart rate, sleep, and SpO2. 7-day battery life.',
    category: 'wearables',
    brand: 'Garmin',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/fitness-tracker',
    affiliate_partner: 'amazon',
    price: 149.99,
    price_currency: 'USD',
    contextual_trigger: 'feature_adoption',
    trigger_reason: 'You were shown this because you enabled step or heart rate tracking.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: null, max_age: null, sex: null, tiers: null, goals: null },
    created_at: '2024-01-01T00:00:00Z',
  },

  // Recovery
  {
    id: 'prod_recov_001',
    name: 'Percussion Massage Gun',
    description: 'Deep tissue percussion therapy. 5 speed settings, 4 attachment heads.',
    category: 'recovery',
    brand: 'Theragun',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/massage-gun',
    affiliate_partner: 'amazon',
    price: 199.00,
    price_currency: 'USD',
    contextual_trigger: 'milestone',
    trigger_reason: 'You were shown this because you completed your first month of consistent training. Recovery tools can help sustain your progress.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: 16, max_age: null, sex: null, tiers: null, goals: null },
    created_at: '2024-01-01T00:00:00Z',
  },

  // Sleep
  {
    id: 'prod_sleep_001',
    name: 'Sleep Sound Machine',
    description: 'White noise, nature sounds, and fan modes. Timer function.',
    category: 'sleep',
    brand: 'LectroFan',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/sound-machine',
    affiliate_partner: 'amazon',
    price: 49.95,
    price_currency: 'USD',
    contextual_trigger: 'feature_adoption',
    trigger_reason: 'You were shown this because you enabled sleep tracking.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: null, max_age: null, sex: null, tiers: null, goals: null },
    created_at: '2024-01-01T00:00:00Z',
  },

  // Personal Care
  {
    id: 'prod_care_001',
    name: 'Mineral Sunscreen SPF 50',
    description: 'Broad-spectrum mineral sunscreen. Reef-safe, non-comedogenic.',
    category: 'personal_care',
    brand: 'Supergoop',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/sunscreen',
    affiliate_partner: 'amazon',
    price: 22.00,
    price_currency: 'USD',
    contextual_trigger: 'seasonal',
    trigger_reason: 'You were shown this because it is spring/summer -- a great time to protect your skin.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: null, max_age: null, sex: null, tiers: null, goals: null },
    created_at: '2024-01-01T00:00:00Z',
  },

  // Kitchen
  {
    id: 'prod_kit_001',
    name: 'High-Speed Blender',
    description: 'Professional-grade blender for smoothies, soups, and meal prep.',
    category: 'kitchen',
    brand: 'Vitamix',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/blender',
    affiliate_partner: 'amazon',
    price: 289.95,
    price_currency: 'USD',
    contextual_trigger: 'behavior_pattern',
    trigger_reason: 'You were shown this because you frequently log smoothies and shakes in your food diary.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: null, max_age: null, sex: null, tiers: null, goals: null },
    created_at: '2024-01-01T00:00:00Z',
  },

  // Mental Wellness
  {
    id: 'prod_mental_001',
    name: 'Light Therapy Lamp (10,000 Lux)',
    description: 'Full-spectrum light therapy for seasonal mood support. UV-free.',
    category: 'mental_wellness',
    brand: 'Verilux',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/light-therapy',
    affiliate_partner: 'amazon',
    price: 39.95,
    price_currency: 'USD',
    contextual_trigger: 'seasonal',
    trigger_reason: 'You were shown this because it is fall/winter -- light therapy can support seasonal mood.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: null, max_age: null, sex: null, tiers: null, goals: null },
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'prod_mental_002',
    name: 'Guided Wellness Journal',
    description: 'Structured daily journal with prompts for gratitude, goals, and reflection.',
    category: 'mental_wellness',
    brand: 'Intelligent Change',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/journal',
    affiliate_partner: 'amazon',
    price: 25.00,
    price_currency: 'USD',
    contextual_trigger: 'milestone',
    trigger_reason: 'You were shown this because you completed your first month. Journaling can deepen your wellness practice.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: null, max_age: null, sex: null, tiers: null, goals: null },
    created_at: '2024-01-01T00:00:00Z',
  },

  // Food Delivery
  {
    id: 'prod_food_001',
    name: 'Macro-Counted Meal Delivery',
    description: 'Chef-prepared meals with exact macro counts. Weekly subscription.',
    category: 'food_delivery',
    brand: 'Factor',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/factor-meals',
    affiliate_partner: 'factor',
    price: null,
    price_currency: 'USD',
    contextual_trigger: 'behavior_pattern',
    trigger_reason: 'You were shown this because your logging patterns suggest limited time for meal prep.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: 18, max_age: null, sex: null, tiers: null, goals: null },
    created_at: '2024-01-01T00:00:00Z',
  },

  // Apparel
  {
    id: 'prod_app_001',
    name: 'Performance Training Shoes',
    description: 'Versatile training shoe for gym, running, and cross-training.',
    category: 'apparel',
    brand: 'Nike',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/training-shoes',
    affiliate_partner: 'amazon',
    price: 120.00,
    price_currency: 'USD',
    contextual_trigger: 'goal_onboarding',
    trigger_reason: 'You were shown this because you set an active fitness goal.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: null, max_age: null, sex: null, tiers: null, goals: ['LOSE', 'GAIN', 'RECOMP'] },
    created_at: '2024-01-01T00:00:00Z',
  },

  // Books
  {
    id: 'prod_book_001',
    name: 'The Renaissance Diet 2.0',
    description: 'Evidence-based nutrition guide for body composition and performance.',
    category: 'books',
    brand: 'RP Strength',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/rp-book',
    affiliate_partner: 'amazon',
    price: 29.99,
    price_currency: 'USD',
    contextual_trigger: 'feature_adoption',
    trigger_reason: 'You were shown this because you are actively tracking nutrition.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: null, max_age: null, sex: null, tiers: ['precision', 'structured'], goals: null },
    created_at: '2024-01-01T00:00:00Z',
  },

  // Outdoor
  {
    id: 'prod_out_001',
    name: 'Running Hydration Vest',
    description: 'Lightweight vest with 1.5L reservoir. Reflective details for visibility.',
    category: 'outdoor',
    brand: 'Nathan',
    image_uri: null,
    affiliate_url: 'https://example.com/affiliate/hydration-vest',
    affiliate_partner: 'amazon',
    price: 64.99,
    price_currency: 'USD',
    contextual_trigger: 'feature_adoption',
    trigger_reason: 'You were shown this because you log outdoor running activities.',
    disclosures: [AFFILIATE_DISCLOSURE],
    demographic_filters: { min_age: null, max_age: null, sex: null, tiers: null, goals: null },
    created_at: '2024-01-01T00:00:00Z',
  },
];

// Category metadata for browsing
export const PRODUCT_CATEGORIES: Array<{
  id: string;
  label: string;
  icon: string;
  count: number;
}> = [
  { id: 'body_composition', label: 'Body Composition', icon: 'scale-outline', count: MARKETPLACE_PRODUCTS.filter((p) => p.category === 'body_composition').length },
  { id: 'nutrition_tools', label: 'Nutrition Tools', icon: 'nutrition-outline', count: MARKETPLACE_PRODUCTS.filter((p) => p.category === 'nutrition_tools').length },
  { id: 'supplements', label: 'Supplements', icon: 'flask-outline', count: MARKETPLACE_PRODUCTS.filter((p) => p.category === 'supplements').length },
  { id: 'hydration', label: 'Hydration', icon: 'water-outline', count: MARKETPLACE_PRODUCTS.filter((p) => p.category === 'hydration').length },
  { id: 'strength_equipment', label: 'Strength Equipment', icon: 'barbell-outline', count: MARKETPLACE_PRODUCTS.filter((p) => p.category === 'strength_equipment').length },
  { id: 'cardio_equipment', label: 'Cardio Equipment', icon: 'bicycle-outline', count: MARKETPLACE_PRODUCTS.filter((p) => p.category === 'cardio_equipment').length },
  { id: 'wearables', label: 'Wearables', icon: 'watch-outline', count: MARKETPLACE_PRODUCTS.filter((p) => p.category === 'wearables').length },
  { id: 'recovery', label: 'Recovery', icon: 'fitness-outline', count: MARKETPLACE_PRODUCTS.filter((p) => p.category === 'recovery').length },
  { id: 'sleep', label: 'Sleep', icon: 'moon-outline', count: MARKETPLACE_PRODUCTS.filter((p) => p.category === 'sleep').length },
  { id: 'personal_care', label: 'Personal Care', icon: 'body-outline', count: MARKETPLACE_PRODUCTS.filter((p) => p.category === 'personal_care').length },
  { id: 'kitchen', label: 'Kitchen', icon: 'restaurant-outline', count: MARKETPLACE_PRODUCTS.filter((p) => p.category === 'kitchen').length },
  { id: 'mental_wellness', label: 'Mental Wellness', icon: 'happy-outline', count: MARKETPLACE_PRODUCTS.filter((p) => p.category === 'mental_wellness').length },
  { id: 'food_delivery', label: 'Food Delivery', icon: 'fast-food-outline', count: MARKETPLACE_PRODUCTS.filter((p) => p.category === 'food_delivery').length },
  { id: 'apparel', label: 'Apparel', icon: 'shirt-outline', count: MARKETPLACE_PRODUCTS.filter((p) => p.category === 'apparel').length },
  { id: 'books', label: 'Books', icon: 'book-outline', count: MARKETPLACE_PRODUCTS.filter((p) => p.category === 'books').length },
  { id: 'outdoor', label: 'Outdoor', icon: 'trail-sign-outline', count: MARKETPLACE_PRODUCTS.filter((p) => p.category === 'outdoor').length },
];

// Sample influencer data
export const SAMPLE_INFLUENCERS: Influencer[] = [
  {
    id: 'inf_001',
    name: 'Alex Rivera',
    partner_code: 'ALEXFIT',
    niche: ['Fitness', 'Strength Training'],
    storefront_name: 'Alex Rivera Fitness',
    bio: 'Certified strength coach and nutrition enthusiast. Helping you build strength and confidence through evidence-based training.',
    profile_image_uri: null,
    commission_rate: 0.10,
    platform_cut_rate: 0.18,
    products: [
      {
        product_id: 'prod_str_001',
        product: MARKETPLACE_PRODUCTS.find((p) => p.id === 'prod_str_001')!,
        influencer_affiliate_code: 'ALEXFIT-BF001',
        influencer_disclosure: {
          type: 'influencer_brand',
          text: 'Alex Rivera has a paid relationship with Bowflex. They may earn a commission on purchases.',
        },
        platform_disclosure: {
          type: 'platform_commission',
          text: 'DUB_AI earns a portion of this commission.',
        },
      },
      {
        product_id: 'prod_supp_001',
        product: MARKETPLACE_PRODUCTS.find((p) => p.id === 'prod_supp_001')!,
        influencer_affiliate_code: 'ALEXFIT-ON001',
        influencer_disclosure: {
          type: 'influencer_brand',
          text: 'Alex Rivera has a paid relationship with Optimum Nutrition. They may earn a commission on purchases.',
        },
        platform_disclosure: {
          type: 'platform_commission',
          text: 'DUB_AI earns a portion of this commission.',
        },
      },
    ],
    approved: true,
    approved_date: '2024-01-15T00:00:00Z',
    violation_count: 0,
  },
  {
    id: 'inf_002',
    name: 'Mia Chen',
    partner_code: 'MIAWELLNESS',
    niche: ['Wellness', 'Recovery', 'Sleep'],
    storefront_name: 'Mia Chen Wellness',
    bio: 'Holistic wellness advocate focused on recovery, sleep optimization, and mental health. Science-backed, never gimmicky.',
    profile_image_uri: null,
    commission_rate: 0.08,
    platform_cut_rate: 0.15,
    products: [
      {
        product_id: 'prod_recov_001',
        product: MARKETPLACE_PRODUCTS.find((p) => p.id === 'prod_recov_001')!,
        influencer_affiliate_code: 'MIAW-TG001',
        influencer_disclosure: {
          type: 'influencer_brand',
          text: 'Mia Chen has a paid relationship with Theragun. They may earn a commission on purchases.',
        },
        platform_disclosure: {
          type: 'platform_commission',
          text: 'DUB_AI earns a portion of this commission.',
        },
      },
      {
        product_id: 'prod_sleep_001',
        product: MARKETPLACE_PRODUCTS.find((p) => p.id === 'prod_sleep_001')!,
        influencer_affiliate_code: 'MIAW-LF001',
        influencer_disclosure: {
          type: 'influencer_brand',
          text: 'Mia Chen has a paid relationship with LectroFan. They may earn a commission on purchases.',
        },
        platform_disclosure: {
          type: 'platform_commission',
          text: 'DUB_AI earns a portion of this commission.',
        },
      },
    ],
    approved: true,
    approved_date: '2024-02-01T00:00:00Z',
    violation_count: 0,
  },
];
